server:
  port: 9999
spring:
  datasource:
    password: postgres
    tomcat:
      initial-size: 1
      max-active: 1
      max-idle: 1
      min-idle: 1
    url: jdbc:postgresql://localhost:5432/db_products?ApplicationName=ProductMS
    username: postgres
  devtools:
    add-properties: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    password: postgres
    url: jdbc:postgresql://localhost:5432/db_products?ApplicationName=ProductMS+Flyway
    user: postgres
    validate-on-migrate: true
  jmx:
    enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: America/Recife
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
